In [1]:
import numpy as np


In [9]:
# Ejercicio 1

lista = list(np.random.randn(10))
for elemento in lista:
    if elemento<0:
        print(elemento)

-1.0505438010082082
-0.6546441470558257
-0.21202496113667757


In [15]:
# Ejercicio 2

matriz = np.random.randn(3,3)
matriz

array([[ 1.95280721, -0.34250595, -1.03045695],
       [ 0.0601603 , -1.66640947,  0.5989859 ],
       [-0.17304928,  0.59141424, -0.64401664]])

In [18]:
# Ejercicio 3

A = np.random.randint(0,100,(3,3))
B = np.random.randint(0,100,(3,1))
C = np.random.randint(0,100,(3,1))

resultado = A*B+C
resultado


array([[8568, 1988, 1424],
       [1046,  452, 3125],
       [ 123,  113,   25]])

In [24]:
# Ejercicio 4

lista = []
for i in range(1,101):
    lista.append(i)

for elemento in lista:
    if (elemento%3)==0:
        ind = lista.index(elemento)
        lista[ind] = 'm3'
        

lista   



[1,
 2,
 'm3',
 4,
 5,
 'm3',
 7,
 8,
 'm3',
 10,
 11,
 'm3',
 13,
 14,
 'm3',
 16,
 17,
 'm3',
 19,
 20,
 'm3',
 22,
 23,
 'm3',
 25,
 26,
 'm3',
 28,
 29,
 'm3',
 31,
 32,
 'm3',
 34,
 35,
 'm3',
 37,
 38,
 'm3',
 40,
 41,
 'm3',
 43,
 44,
 'm3',
 46,
 47,
 'm3',
 49,
 50,
 'm3',
 52,
 53,
 'm3',
 55,
 56,
 'm3',
 58,
 59,
 'm3',
 61,
 62,
 'm3',
 64,
 65,
 'm3',
 67,
 68,
 'm3',
 70,
 71,
 'm3',
 73,
 74,
 'm3',
 76,
 77,
 'm3',
 79,
 80,
 'm3',
 82,
 83,
 'm3',
 85,
 86,
 'm3',
 88,
 89,
 'm3',
 91,
 92,
 'm3',
 94,
 95,
 'm3',
 97,
 98,
 'm3',
 100]

In [25]:
# Ejercicio 9

D = np.array([[3, 2], [1, 4]])
E = np.array([[1], [0]])
F = np.array([[0], [1]])
G = np.array([[1], [1]])

result_E = np.dot(D, E)
result_F = np.dot(D, F)
result_G = np.dot(D, G)

print("Resultado de D * E:")
print(result_E)

print("Resultado de D * F:")
print(result_F)

print("Resultado de D * G:")
print(result_G)

eigenvalues, eigenvectors = np.linalg.eig(D)

print("Autovalores:")
print(eigenvalues)

print("Autovectores:")
print(eigenvectors)


Resultado de D * E:
[[3]
 [1]]
Resultado de D * F:
[[2]
 [4]]
Resultado de D * G:
[[5]
 [5]]
Autovalores:
[2. 5.]
Autovectores:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
